name: CD - Deploy Frontend to DockerHub

# Deployment manual por ambiente
on:
  workflow_dispatch:
    inputs:
      ambiente:
        description: "Selecciona el ambiente de despliegue"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Descarga el cÃ³digo del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short Git SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login a Docker Hub con Access Token
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Build de la imagen frontend y push al registry (dev/qa - sin latest)
      - name: Build & Push Docker image (dev/qa)
        if: github.event.inputs.ambiente != 'prod'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jobdirect-app:${{ github.event.inputs.ambiente }}
            ${{ secrets.DOCKERHUB_USERNAME }}/jobdirect-app:${{ steps.vars.outputs.SHORT_SHA }}

      # Build de la imagen frontend y push al registry (prod - con latest)
      - name: Build & Push Docker image (prod)
        if: github.event.inputs.ambiente == 'prod'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jobdirect-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/jobdirect-app:${{ steps.vars.outputs.SHORT_SHA }}
