name: Build & Push Frontend to DockerHub

# Se ejecuta cuando hay cambios en main
on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    # Runner Linux
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura el motor de build de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login a Docker Hub con Access Token
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build de la imagen frontend y push al registry
      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .                # Carpeta donde está el Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/jobdirect-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/jobdirect-app:${{ github.sha }}
